### ISSUE TITLE
Optimisation du temps de lancement de l'appli iOS PagesJaunes

### ISSUE THREAD

**Issue by mackoj** [mackoj/ConfTV#2]
# Optimisation du temps de lancement de l'appli iOS PagesJaunes

Juillet 2017 - @yellowgmk - @jgodon - @jmacko - @macistador - @jdatour 

---

# Contexte

Une dégradation progressive du temps de lancement moyen de l'application PagesJaunes iOS a été constatée lors de la mise en production des trois dernières versions. Or, plus une appli est lente à démarrer, plus on prend le risque de perdre des utilisateurs que ce soit en visite direct ou en visite indirecte (SEO ou Apple Plans par exemple).

Ce que l'on mesure aujourd'hui c'est la durée moyenne du *report value* **start** remontré par *Dynatrace*. Gloablement, c'est le temps écoulé entre le démarage du SDK Dynatrace (après initialisation de l'application, voire le chapitre concernant le *pre-main*) et l'affichage de la page d'accueil (HP).

L'augmentation de ce temps de lancement est liée à plusieurs choses : l'accumulation de fonctionnalités, souvent de SDK externes que nous ne maitrisons pas ainsi qu'à une hausse de la complexité de certains traitements ou calculs. Ces ajouts sont parfois fait sans prendre le temps d'optimiser le code existant afin de le rendre optimal en terme de complexité algorithmique, ni de nettoyer ce qui ne sert plus ou très peu et sans s'assurer que le jeu en vaut la chandelle (telle fonctionnnalité gaut elle une seconde de plus au démarrage de l'appli par exemple ?).

**En moyenne, Dynatrace nous montre que 80% de nos utilisateurs lancent l'application iOS 8.6 en moins de de 3,5 secondes.**

![dynatrace_black](https://user-images.githubusercontent.com/8012050/28922196-6d0ed8be-7859-11e7-9f63-6cbe351a92dd.png)

# Objectifs

L'objectif du chantier *"Optimisation du temps de lancement"* qui nous a été fixé est la réduction du temps de lancement de l'application PagesJaunes iOS de 40% soit un total de 2 secondes en moyenne pour 80% de nos utilisateurs, tout devices confondus.
C'est un objectif ambitieux que nous pensons difficile à atteindre à moins de nettoyer/supprimer certain fonctionnel de l'appli et certain SDK (Accengage, Ezeeworld & Appsee par exemple). Cependant, conscient que nous devons trouver un juste milieu entre les besoins techniques et les besoins business de l'appli, nous allons tout mettre en oeuvre pour s'en approcher le plus possible sans pour autant faire table rase de l'existant.

Petit rappel: *"Apple suggest to aim for a total app launch time of under 400ms and you must do it in less than 20 seconds or the system will kill your app"*

---

# Mesures

## Quelques précisions

Les mesures en production sont réalisées avec Dynatrace (n.b. ce temps est le temps *post-main*, donc en deça de la réalité puisqu'il faut ajouter à cela le temps pre-main pendant lequel le système charge -entre autre- les librairies embarquées). Pour mesurer ce temps, nous devons être en *mode debug* ce qui ne permet pas d'utiliser toutes les optimisations de compilation d'une version *release* et ajoute également de nombreux *logs*. Les mesures réalisées en mode *debug* sont donc bien supérieures à celles constatées en production. Cependant ces chiffres restent des indicateurs fiables pour observer son évolution.

![dynatrace](https://user-images.githubusercontent.com/8012050/28922242-992156a2-7859-11e7-83ca-3be557d2b65d.png)

## Mesurer Quoi ?

Afin de savoir ce qui prend du temps (même sur des *thread en background* cela prend du CPU et donc ralenti les autres traitements réalisés en parallèle), nous observons plusieurs partie du code exécuté au démarage de l'app. 

Voici la liste exhaustive des mesures de la version 8.6 de l'app avec leur temps maximum pour **80% des utilisateurs tout devices confondus**. Ces chiffres sont donnés par **Dynatrace**, en **millisecondes**.
*(Cela peut se traduire par: pour 80% des utilisateurs de l'appli PagesJaunes, le StatsKit s'initilise en moins de secondes.*

### AppDelegate

start | willFinishLaunching 
----- | ------------------- 
3300 | 1800
 

### SDKs

CIMobKit | StatsKit | Dynatrace | Gigya | Accengage | CoreData | Realm | Appsee | Crashlytics | EzeeWorld
-------- | -------- | --------- | ----- | --------- | -------- | ----- | ------ | ----------- | --------- 
10 | 80 | 170 | 80 | 70 | 60 | 350 | 25 | 200 | x

### Divers : ViewControllers, AppRouter...

AppRouter | Search Tab | History Tab | Favorites Tab | Account Tab
--------- | ---------- | ----------- | ------------- | -----------
480 |

**// TODO: compléter avec les temps remontés par la prod en 8.7**

Pour la version 8.7 de l'application, nous avons ajouter les mesures suivantes:

Shared Cache Manager refresh | Send Starting Stats | Resume Photos Uploads | AppRouter External Open Screen | Synchronize Favorites | AppsFlyer | facebook | HP Shortcuts Auto | HP viewDidLoad | HP viewWillAppear
---------------------------- | ------------------- | --------------------- | ------------------------------ | --------------------- | --------- | -------- | ----------------- | -------------- | -----------------
x | x | x | x | x | x | x | x | x | x 

### Outils : Dynatrace, Performance tool & Instruments

// TODO: ajouter un tutoriel de l'outil Performance de Guillaume couplé à Instrument

Pour nos mesures, nous utilisons la solution **DynatraceUEM**, couplée à la classe **Performance** implémentée dans l'application. Elle nous permet à la fois d'envoyer des *reportValue* à Dynatrace en production mais également de visualiser dans l'outil **Time Profiler** d'Instruments dans Xcode avec des labels compréhensibles et en couleurs les différentes exécutions de morceaux de codes que l'on souhaite mesurer.

Guillaume à généré un **template pour Instruments** pour améliorer la visiblité dans l'outil d'Apple : 

[Template Instruments](https://github.com/PagesjaunesMobile/iOS-PagesJaunes/files/1197223/Analyse.du.temps.de.demarrage.OK.zip)

---

# Tâches à effectuer

## Pré-main @jmacko

Ce temps n'est pas mesuré aujourd'hui mais il contribue fortement au temps de lancement de l'application (sur un iPhone 7 par exemple il est supérieur au temps du *post-main*).
L'enjeu de cette première partie est justement de le mesurer puis de le faire diminuer autant que faire se peu.

### Trie / Nettoyage

Le plus simple serait quand même de *pruner* le plus de SDK / librairies / frameworks (appellez-les comme vous voulez) possibles. Cependant, conscient du besoin de certain fonctionnels de l'app, il faut savoir le faire avec délicatesse et diplomatie...

Nous avons une **quarantaine de pods** dans le Podfile...

- Lister les librairies/SDK 
- Étudier lesquelles on garde, lesquelles on migre en swift si elles sont en Objective-C et lesquelles qu'on supprimerait. 
Par exemple on pourrait supprimer AFNetworking, FXReachability, Accengage (oups !), Appsee, Swinject, BeaconForStoreSDK, etc... Si cela est pertinent, nous devons envisager ces possiblités...

- En règle général, à l'avenir il faudrait systématiquement se poser la question avant d'ajouter la moindre librairie à l'application, le moindre SDK, etc... Le strict minimum nécesssaire ONLY... Car plus on utilise de frameworks liés à l'app, plus ce temps augmente, il y a donc un intérêt à limiter le nombre de frameworks externes initialisés.

### Rebase/binding time 

- **Plus on a de symboles** dans l'application, **plus le temps de lancement lié au linker est long**.

Nous devons donc travailler à la réduction de ces symboles :

- Lister, supprimer ou migrer les librairies en Objective-C
- Certaines bibliothèques font appels à une **initialisation préalable au démarrage de l'app** (méthode +[NSObject load], exécutée avant main()), bien que ce ne soit pas conseillé (AFNetworking / 52 ms, AsyncDisplayKit / 53 ms, Accengage / 77 ms (en 8.0 uniquement), Tweaks 158 ms (!!!) ).
- Voir si les Tweaks peuvent être nettoyés et/ou la librairie **FBTweaks** remplacée par un code plus moderne, en Swift et plus optimisé

### Dynamic Library (Dylb) 

L'une des principales problématiques est celle des librairies dynamiques qui sont chargées par le système au démarage de l'application avant que nous ayons la main dessus...
Cependant, nous devons être en mesure de mesurer ce temps. 

N.B. Cocher le **DYLD\_PRINT\_STATISTICS** dans le scheme

#### Mesures

- L'outil **Time profiler** indique le temps d'initilisation...
- Nous pouivons aussi parser la sortie Xcode et stocker/uploader ces mesures

- https://useyourloaf.com/blog/slow-app-startup-times/

Exemple:

Total pre-main time: 952.33 milliseconds (100.0%) 
	dylib loading time: 184.65 milliseconds (19.3%)
	rebase/binding time: 490.21 milliseconds (51.4%) 
		ObjC setup time: 124.23 milliseconds (13.0%)
		initializer time: 153.14 milliseconds (16.0%) 
		slowest intializers :
			libSystem.dylib : 2.57 milliseconds (0.2%) 
			AFNetworking : 20.23 milliseconds (2.1%)
			Accengage : 62.66 milliseconds (6.5%) 
			AsyncDisplayKit : 53.58 milliseconds (5.6%)
			Tracker : 23.87 milliseconds (2.5%)

#### Compilation

- Compiler les dépendances en **librairies statiques** : 

	- https://blog.automatic.com/how-we-cut-our-ios-apps-launch-time-in-half-with-this-one-cool-trick-7aca2011e2ea
	- https://pewpewthespells.com/blog/static_and_dynamic_libraries.html
	- https://github.com/keith/swift-staticlibs (deprecated si on passe sur Xcode 9)
	
-  Charger les *frameworks* a la main

*Link against all frameworks using -weak_framework and invoke dlopen during the run of the app (the example app does this). You'll need to ensure the framework is loaded before using any symbols from it. You will still take the dyld performance hit, but this gives you flexibility when the hit happens.* https://github.com/nicklockwood/GZIP/issues/24

#### Configuration

- Passer la **version minimum** supportée de l'OS à iOS 9.3 et configurer quelques ptites choses : https://github.com/stepanhruda/dyld-image-loading-performance

Here is an example app launch comparison, profiled on an iPad Air 2:

**// iOS 9.2**
total time: 4.7 seconds (100.0%)
...
total images loading time: **3.9 seconds** (82.5%)

**// iOS 9.3 beta 2**
total time: 1.7 seconds (100.0%)
...
total images loading time: **1.2 seconds** (73.2%)

#### Cocoapods ?

- Voir ce que **Amimono** (https://github.com/Ruenzuo/cocoapods-amimono) peut faire pour nous aider à *"Move all dynamic frameworks symbols into the main executable."*
- Voir ce que **accelerator** (https://github.com/johnno1962/Accelerator) peut faire pour nous...

---

## Post-main @macistador - @jdatour

Après avoir vu ce que l'on pouvait optimiser dans l'initialisation *pré-main* de l'application, passsons maintenant à la partie sur laquelle nous avons le plus la main : le code :-)
C'est là que nous avons la plus grande marge de manoeuvre et là que nous pouvons influer sur le ressentis de l'utilisateur...

### Mesures actuelles

On mesure via Dynatrace / Performance.swift / Time profiler / etc...

![timeprofiler_general](https://user-images.githubusercontent.com/8012050/28922273-bb02adfc-7859-11e7-8130-f28e320fec34.png)

### AppDelegate 

- Nous devons concenter nos efforts sur le `willFinishLaunchingWithOptions` car 'init' ne coûte quasiment rien.
- Déplacer le plus de choses possible de l'AppDelegate. Par exemple, tous les SDK qui n'auraient pas de raison d'être initilisés tout de suite. Idem pour certain traitement de données...

Par exemple on pourait avoir une système de file d'attente dans l'appDelegate qui, **à la réception d'une ou plusieurs notifications**, initiliserait les SDK non obligatoires au démarage, processerait les données, etc... 
Cette/ces notification(s) pourai(en)t être envoyée(s) après affichage de la Home Page par exemple... Regardons plus en détail ce qui est **strictement obligatoire au démarrage** de l'application PagesJaunes

![timeprofiler](https://user-images.githubusercontent.com/8012050/28922298-d52084b6-7859-11e7-9bc5-5503853b695a.png)

#### Quelles initilisations obligatoires ?

*Quels SDK, quelles allocations mémoires et quels traitements de données ne peuvent être décalés et sont obligatoires au lancement de l'application avant l'affichage de la Home ?*

- Dynatrace
- CrashLytics (Fabric)
- StatsKit
	- Son initialisation pourrait être décallée après l'affichage de la Home mais cela pourrait poser de sérieux problèmes (décallage de l'envoi des tags de stats de lancement de l'application, des configurations en place, de l'affichage de la Home, etc... Cela nécessiterait des modifications non négligeables et surtout risquées. À envisager mais peut-être dans un deuxième temps.
	- Une autre solution envisagée: utiliser un générateur de code pour le StatsKit au lieu de parser des fichiers XML au démarrage.
- AppRouter (TabBar, viewcontrollers comme la HP, etc...)

#### Qui décaler après l'affichage de la Home Page ?

- [ ] Appsee
- [ ] Accengage
- [ ] CiMobKit
- [ ] Realm
- [ ] CoreData
- [ ] Accengage
- [ ] Refresh cacheModel et chargement des données de l'autocompletion (historique des recherches)
- [ ] Resume upload photos
- [ ] Synchronisation des favoris
- [ ] AppsFlyer
- [ ] Calculs des raccourcis de la Home pour la ZSM (ShortcutRanking...)
- [ ] EzeeWorld
- [ ] Gigya

Par exemple, on voit dans le graphe ci-dessous que le SDK Appsee coute après son initialisation :

![appsee_thread](https://user-images.githubusercontent.com/8012050/28922260-b04055fe-7859-11e7-8ab6-356e919f7a34.png)

### View controllers

Il faut que les 4 view controllers initialisés à la création de leur navigation controller par la TabBar ne fassent pas leur calculs et toutes leurs initialisations/allocations dans le *viewDidLoad* (ou alors le minimum possible) mais qu'ils le fassent au maximum à l'affichage de leur vue (*viewDidAppear*.)

**Quelles modifications possibles dans quel View Controller ?**

#### Home Page

- Dans le cas de la **Home Page** par exemple on pourrait imaginer que les Zone Sous le Moteur / Zone d'Action Interompues / Zone d'Actions Engageantes soient initialisées et calculées seulement une fois que la HP est affichée, puis au fur et à mesure de leur création on pourrait les faire arriver de manière jolie (animation de translation de bas en haut / fadding / etc...) ce qui de plus indiquerait à l'utilisateur qu'il y a quelque chose en dessous. 
- On peut aussi imaginer afficher uniquement l'image du background, puis ajouter les éléments comme le moteur, les boutons, le logo, etc... une fois la HP affichée (et la *report value* start envoyé du coup :p)

#### Compte

---

## Options de compilation **@mika**

- Quelles options de compilation permettent de meilleures performances au démarage et au dépends de qui/quoi ?
- Verifier que cela n'occasionne pas de crash...

---

## Points de vigilence

Nous devons être extrêment vigilants à ne pas introduire de regression dans l'application, cela va de soit, et plus particulièrement :

- sur l'envoi de statistiques
- sur l'ouverture externe de l'application en FD
- sur le tunel d'intro

---

# References

## Général
- https://videos.raywenderlich.com/courses/74-practical-instruments/lessons/1
- https://developer.apple.com/videos/play/wwdc2016/411/
- https://developer.apple.com/videos/play/wwdc2017/413/
- https://developer.apple.com/videos/play/wwdc2016/406/
- https://developer.apple.com/videos/play/wwdc2016/418/
- https://useyourloaf.com/blog/slow-app-startup-times/

## Dynamic librairies
- https://blog.automatic.com/how-we-cut-our-ios-apps-launch-time-in-half-with-this-one-cool-trick-7aca2011e2ea
- https://github.com/Ruenzuo/cocoapods-amimono
- https://pewpewthespells.com/blog/static_and_dynamic_libraries.html
- https://github.com/keith/swift-staticlibs
- https://github.com/stepanhruda/dyld-image-loading-performance
- https://github.com/johnno1962/Accelerator
- http://www.openradar.me/radar?id=6332266275930112
- https://github.com/artsy/eigen/issues/1246
- https://github.com/nicklockwood/GZIP/issues/24

## Études existantes
- https://wiki.services.local/display/PMMOBILES/U+-+07+-+Performance+lancement+App
- https://wiki.services.local/download/attachments/78840333/Analyse%20des%20performances%20de%20démarrage%20iOS.pdf?version=1&modificationDate=1486999701018&api=v2
- https://wiki.services.local/download/attachments/78840333/pre-main-time.pdf?version=1&modificationDate=1486999926989&api=v2

**Comment by teriiehina** [comment]
:+1:
